### ISSUE TITLE
代码公开

### ISSUE THREAD

**Issue by Lensty** [darkseid-arch/AGFE-Net#1]
请问什么时候能公开数据集和代码呢

**Comment by darkseid-arch** [comment]
亲爱的学者您好，
我个人目前位于西安市，由于最近疫情吃紧，我已被疫情隔离管控，无法前往实验室，等我解封后第一时间上传代码给各位共享，给大家造成的不便请谅解。
祝您生活愉快


| |
王振
|
|
***@***.***
|
在2022年1月5日 ***@***.***> 写道：

请问什么时候能公开数据集和代码呢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lensty** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    感谢，请问是否方便加微信交流一下，我的微信：L878732309
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                878732309
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年1月5日 ***@***.***> 写道： 




亲爱的学者您好，

我个人目前位于西安市，由于最近疫情吃紧，我已被疫情隔离管控，无法前往实验室，等我解封后第一时间上传代码给各位共享，给大家造成的不便请谅解。

祝您生活愉快





| |

王振

|

|

***@***.***

|

在2022年1月5日 ***@***.***> 写道：



请问什么时候能公开数据集和代码呢



—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by darkseid-arch** [comment]
加你了


| |
王振
|
|
***@***.***
|
在2022年1月5日 ***@***.***> 写道：







font{
line-height: 1.6;
}
ul,ol{
padding-left: 20px;
list-style-position: inside;
}



感谢，请问是否方便加微信交流一下，我的微信：L878732309

















878732309




***@***.***








签名由
网易邮箱大师
定制



在2022年1月5日 ***@***.***> 写道：




亲爱的学者您好，

我个人目前位于西安市，由于最近疫情吃紧，我已被疫情隔离管控，无法前往实验室，等我解封后第一时间上传代码给各位共享，给大家造成的不便请谅解。

祝您生活愉快





| |

王振

|

|

***@***.***

|

在2022年1月5日 ***@***.***> 写道：



请问什么时候能公开数据集和代码呢



—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
